server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  types { application/octet-stream parquet; }
  location / { try_files $uri $uri/ /index.html; }
  location /data/ { autoindex off; add_header Cache-Control "no-store"; }
}
