import type cytoscape from "cytoscape";
import { HIDE_LABEL_BELOW_PX } from "../map/legibility";

const FONT = 'system-ui, -apple-system, "Segoe UI", Roboto, "Apple SD Gothic Neo", "Noto Sans KR", sans-serif';

/** Node fill is the entity type; communities are containers; the accent only marks the selection. */
export const GRAPH_STYLE = [
  {
    selector: "node",
    style: {
      "background-color": "data(color)",
      "border-width": 1.5,
      "border-color": "#ffffff",
      label: "data(label)",
      "font-family": FONT,
      "font-size": 11,
      color: "#1b2430",
      "text-valign": "bottom",
      "text-halign": "center",
      "text-margin-y": 5,
      "text-wrap": "ellipsis",
      "text-max-width": 120,
      "text-background-color": "#ffffff",
      "text-background-opacity": 0.85,
      "text-background-padding": 2,
      "text-background-shape": "roundrectangle",
      "min-zoomed-font-size": 6,
      "overlay-opacity": 0,
    },
  },
  { selector: "node[size]", style: { width: "data(size)", height: "data(size)" } },
  { selector: "node.bundle", style: { shape: "round-rectangle", "background-opacity": 0.35, "border-width": 2, "border-style": "double", "border-color": "data(color)", "font-weight": 600 } },
  { selector: "edge.faint", style: { opacity: 0.35 } },
  { selector: "edge.faint.in, edge.faint.out, edge.faint.picked, edge.faint.hover", style: { opacity: 1 } },
  { selector: "node.ghost", style: { "background-color": "#ffffff", "border-color": "data(color)", "border-width": 1.5, "border-style": "dashed", color: "#5f6b78" } },
  {
    selector: "node:parent",
    style: {
      "background-color": "data(fill)",
      "background-opacity": 0.55,
      "border-width": 1.5,
      "border-color": "#b9c6ae",
      shape: "round-rectangle",
      padding: 28,
      label: "data(label)",
      "font-size": 12,
      "font-weight": 600,
      "text-valign": "top",
      "text-halign": "center",
      "text-margin-y": -8,
      "text-wrap": "wrap",
      "text-overflow-wrap": "anywhere",
      "text-max-width": 320,
      "text-background-opacity": 0,
      "min-zoomed-font-size": HIDE_LABEL_BELOW_PX,
      "overlay-opacity": 0,
    },
  },
  {
    selector: "edge",
    style: {
      width: 1.2,
      "line-color": "#b8c0c8",
      "target-arrow-color": "#b8c0c8",
      "target-arrow-shape": "triangle",
      "arrow-scale": 0.7,
      "curve-style": "bezier",
      "control-point-step-size": 40,
      label: "",
      "font-family": FONT,
      "font-size": 9.5,
      color: "#5f6b78",
      "text-rotation": "autorotate",
      "text-background-color": "#ffffff",
      "text-background-opacity": 0.9,
      "text-background-padding": 2,
      "text-margin-y": -7,
      "overlay-opacity": 0,
    },
  },
  { selector: "edge.boundary", style: { "line-style": "dashed", "line-dash-pattern": [4, 3], "line-color": "#cfd5db", "target-arrow-color": "#cfd5db" } },
  { selector: "node.quiet", style: { label: "" } },
  { selector: ".faded", style: { opacity: 0.12, "text-opacity": 0 } },
  { selector: "node:parent.faded", style: { opacity: 0.45, "text-opacity": 0.6 } },
  { selector: "node.dim", style: { opacity: 0.18, "text-opacity": 0 } },
  { selector: "node.seed", style: { "border-color": "#3d5afe", "border-width": 3, "font-weight": 600 } },
  { selector: "node.focus", style: { "border-color": "#3d5afe", "border-width": 3, "text-max-width": 320, "font-weight": 600, "z-index": 20 } },
  { selector: "node.neighbor", style: { "z-index": 10 } },
  { selector: "edge.out", style: { "line-color": "#3d5afe", "target-arrow-color": "#3d5afe", width: 1.8, label: "data(type)", "z-index": 9 } },
  { selector: "edge.in", style: { "line-color": "#6b7784", "target-arrow-color": "#6b7784", width: 1.8, label: "data(type)", "z-index": 9 } },
  { selector: "edge.picked", style: { "line-color": "#3d5afe", "target-arrow-color": "#3d5afe", width: 2.5, label: "data(type)", "z-index": 10 } },
  { selector: "edge.hover", style: { label: "data(type)", width: 2, "line-color": "#5f6b78", "target-arrow-color": "#5f6b78" } },
  // Last so it wins over node:parent: with clouds on, the compound box is invisible but still shapes the layout.
  { selector: "node:parent.cloud", style: { "background-opacity": 0, "border-opacity": 0, label: "", "text-opacity": 0 } },
] as unknown as cytoscape.StylesheetStyle[];

export const DEPTH_FILL = ["#eef2ea", "#e2e8dc", "#d5ddcd", "#c8d2bf"];

/** Map view: collapsed communities are labelled boxes; aggregate links carry counts. */
export const MAP_STYLE = [
  ...GRAPH_STYLE,
  {
    selector: "node.collapsed",
    style: {
      shape: "round-rectangle",
      width: "data(w)",
      height: "data(h)",
      "background-color": "data(fill)",
      "background-opacity": 1,
      "border-width": 1.5,
      "border-color": "#b9c6ae",
      label: "data(label)",
      "font-size": 12,
      "font-weight": 600,
      "text-valign": "center",
      "text-halign": "center",
      "text-wrap": "wrap",
      // Governance titles carry raw ids. One unbroken token is wider than any box, and without
      // this it runs straight over the neighbours instead of wrapping.
      "text-overflow-wrap": "anywhere",
      "text-max-width": "data(labelWidth)",
      "text-background-opacity": 0,
      "text-margin-y": 0,
      color: "#1b2430",
      // Below this the label is dropped rather than drawn as a smudge that reads as overlapping text.
      "min-zoomed-font-size": HIDE_LABEL_BELOW_PX,
    },
  },
  { selector: "node.unassigned", style: { "border-style": "dashed", "border-color": "#8c96a0", color: "#5f6b78" } },
  { selector: "node.selected", style: { "border-color": "#3d5afe", "border-width": 3 } },
  { selector: "node:parent.selected", style: { "border-color": "#3d5afe", "border-width": 2.5 } },
  { selector: "edge.agg", style: { width: "data(width)", "line-color": "#c2c9d0", "target-arrow-shape": "none", "curve-style": "straight", opacity: 0.9 } },
  { selector: "edge.agg.loose", style: { "line-style": "dashed", "line-dash-pattern": [3, 4], "line-color": "#d5dbe1", opacity: 0.8 } },
  { selector: "edge.agg.hover, edge.agg.picked", style: { "line-color": "#5f6b78", label: "data(count)", "font-size": 11, "text-rotation": "none", "text-margin-y": 0, opacity: 1 } },
  { selector: "edge.plink", style: { "line-style": "dashed", "line-dash-pattern": [6, 4], "line-color": "#a9b89c", "target-arrow-color": "#a9b89c", "target-arrow-shape": "triangle", "arrow-scale": 0.9, width: 1.4, "curve-style": "bezier" } },
  { selector: "edge.plink.hover", style: { label: "data(type)", "line-color": "#5f6b78", "target-arrow-color": "#5f6b78" } },
] as unknown as cytoscape.StylesheetStyle[];
